openapi: 3.0.2
info:
  version: 2.0.0
  title: Welcome to The Vinter APIs
  termsOfService: 'https://vintercapital.com/tos/'
  contact:
    email: hello@vinter.co
    url: 'https://vinter.co/contact'
    name: contact
  license:
    name: 'Proprietary '
    url: www.vinter.co
  x-logo:
    url: 'https://i.postimg.cc/7Y3fY9V1/vinterlogomedpadding.png'
  description: |
    # Index structure
    There are indexes containing one, or multiple, constituents. These two categories are:
    * single assets
    * multi assets 

    Single asset indexes track the value of a single asset e.g. BTC in USD, whereas multi assets indexes track the value of a portfolio with multiple assets e.g. BTC and XAU. The indexes are offered in three frequencies:

    * real-time (r)
    * hourly (h)
    * daily (d)

    The last letter of the index name indicates its frequency. The `btc-usd-p-d` index is a single asset index with hourly (h) frequency. The `vnby-bold1-d` index is a multi asset index with daily (d) frequency. 

    ### API functionality 
    The core functionality of the Vinter API is to

    1. get symbols for all active index values.  
    2. get current index values and metadata for a symbol.

    By default, the API returns the most recent index value. You can control the number of records returned with the `limit` parameter. 

    ### Try the API
    You can use curl to try out the single assets hourly API

    ```curl 
    curl -H "Authorization: your_secret_api_key" https://www.vinterapi.com/api/v2/single_assets_hourly/?symbol=btc-usd-p-h 
    ```

    In Python you can do this using the request library:


    ```python 
    import requests url = "https://www.vinterapi.com/api/v2/single_assets_hourly/?symbol=btc-usd-p-h" 
    headers = {"Authorization": your_secret_api_key} 
    r = requests.get(url, headers=headers) 
    ```

    ### Request API key
    The active endpoint can be accessed without an API key, all other endpoints require an API key. You can request an API key by sending an email to [hello@vinter.co](mailto:hello@vinter.co)
tags:
  - name: Active multi assets
    description: |
      The active multi assets endpoint returns information on all multi assets. The endpoint returns the index symbols that you can use when you query other endpoints. The endpoint does not require an API key and does not accept any parameters. **Example URL** ``` https://www.vinterapi.com/api/v2/active_multi_assets/ ```'
  - name: Active single assets
    description: 'The active single assets endpoint returns information on all single assets indexes. The endpoint returns the index symbols that you can use when you query other endpoints. The endpoint does not require an API key and does not accept any parameters. **Example URL** ``` https://www.vinterapi.com/api/v2/active_single_assets/ ```'
  - name: Multi assets daily
    description: 'The multi assets daily endpoint returns values for a specific multi asset index that is calculated on a  daily basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/multi_assets_daily/?symbol=vntr-5eq-d ```'
  - name: Multi assets hourly
    description: 'The multi assets hourly endpoint returns values for a specific multi asset index that is calculated on an hourly basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/multi_assets_hourly/?symbol=vntr-5eq-h ```'
  - name: Multi assets real-time
    description: 'The multi assets real-time endpoint returns values on a specific multi asset index that is calculated on a continuous basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/multi_assets_real_time/?symbol=vntr-5eq-r ```'
  - name: Single assets daily
    description: 'The single assets daily endpoint returns values for a specific single asset index that is calculated on a daily basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/single_assets_daily/?symbol=btc-usd-p-d ```'
  - name: Single assets hourly
    description: 'The single assets hourly endpoint returns values for a specific single asset index that is calculated on an hourly basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/single_assets_hourly/?symbol=btc-usd-p-h ```'
  - name: Single assets real-time
    description: 'The single assets real-time endpoint returns values on a specific single asset index that is calculated on a continuous basis. The endpoint requires an API key and it requires that the symbol of the index is specified using the symbol parameter. **Example URL** ``` https://www.vinterapi.com/api/v2/single_assets_real_time/?symbol=btc-usd-p-r ```'
servers:
  - url: 'https://vinterapi.com/api/v2'
paths:
  /active_multi_assets/:
    $ref: paths/active_multi_assets.yaml
  /active_single_assets/:
    $ref: paths/active_single_assets.yaml
  /multi_assets_daily/:
    $ref: paths/multi_assets_daily.yaml
  /multi_assets_hourly/:
    $ref: paths/multi_assets_hourly.yaml
  /multi_assets_real_time/:
    $ref: paths/multi_assets_real_time.yaml
  /single_assets_daily/:
    $ref: paths/single_assets_daily.yaml
  /single_assets_hourly/:
    $ref: paths/single_assets_hourly.yaml
  /single_assets_real_time/:
    $ref: paths/single_assets_real_time.yaml
components:
  securitySchemes:
    Authorization:
      name: API Key
      type: apiKey
      in: header
